db:
  build: ./mysql
  environment:
    MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
  volumes:
    - ./mysql/tmp:/var/lib/mysql
web:
  build: ./web
  ports:
    - 80:80
  volumes:
    - ./web/php:/var/www/html
  links:
    - db:db
